version: "3"

services:
  esplora:
    environment:
      - "TRACING=1"
      - "CYPHERNODE_URL=https://gatekeeper:${GATEKEEPER_PORT}"
    image: blockstream/esplora:latest
    command: "/srv/explorer/run.sh bitcoin-${NETWORK} explorer"
    volumes:
      - "$APP_SCRIPT_PATH/data:/esplora/data"
      - "$GATEKEEPER_DATAPATH/certs/cert.pem:/esplora/cert.pem:ro"
      - "$LOGS_DATAPATH:/esplora/logs"
      - "$BITCOIN_DATAPATH:/data"
    ports:
      - "50001:50001"
      - "3002:80"
    networks:
      - cyphernodeappsnet
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=cyphernodeappsnet

      - traefik.http.routers.esplora.rule=PathPrefix(`/esplora`)
      - traefik.http.routers.esplora.entrypoints=websecure
      - traefik.http.routers.esplora.tls=true
      - traefik.http.routers.esplora.service=esplora
      - traefik.http.routers.esplora.middlewares=esplora-redirectregex@docker,esplora-stripprefix@docker,esplora-auth@docker

      - traefik.http.routers.esplora-onion.rule=PathPrefix(`/esplora`)
      - traefik.http.routers.esplora-onion.entrypoints=onion
      - traefik.http.routers.esplora-onion.service=esplora
      - traefik.http.routers.esplora-onion.middlewares=esplora-redirectregex@docker,esplora-stripprefix@docker,esplora-auth@docker

      - traefik.http.services.esplora.loadbalancer.server.port=3002
      - traefik.http.services.esplora.loadbalancer.passHostHeader=true

      - traefik.http.middlewares.esplora-redirectregex.redirectregex.regex=^(.*)/esplora$$
      - traefik.http.middlewares.esplora-redirectregex.redirectregex.replacement=$$1/esplora/
      - traefik.http.middlewares.esplora-redirectregex.redirectregex.permanent=true
      - traefik.http.middlewares.esplora-stripprefix.stripprefix.prefixes=/esplora,/esplora/
      # - traefik.http.middlewares.esplora-stripprefix.stripprefix.forceSlash=true
      - traefik.http.middlewares.esplora-auth.basicauth.users=<username:bcrypt>
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=cyphernodeappsnet

        - traefik.http.routers.esplora.rule=PathPrefix(`/esplora`)
        - traefik.http.routers.esplora.entrypoints=websecure
        - traefik.http.routers.esplora.tls=true
        - traefik.http.routers.esplora.service=esplora
        - traefik.http.routers.esplora.middlewares=esplora-redirectregex@docker,esplora-stripprefix@docker,esplora-auth@docker

        - traefik.http.routers.esplora-onion.rule=PathPrefix(`/esplora`)
        - traefik.http.routers.esplora-onion.entrypoints=onion
        - traefik.http.routers.esplora-onion.service=esplora
        - traefik.http.routers.esplora-onion.middlewares=esplora-redirectregex@docker,esplora-stripprefix@docker,esplora-auth@docker

        - traefik.http.services.esplora.loadbalancer.server.port=3002
        - traefik.http.services.esplora.loadbalancer.passHostHeader=true

        - traefik.http.middlewares.esplora-redirectregex.redirectregex.regex=^(.*)/esplora$$
        - traefik.http.middlewares.esplora-redirectregex.redirectregex.replacement=$$1/esplora/
        - traefik.http.middlewares.esplora-redirectregex.redirectregex.permanent=true
        - traefik.http.middlewares.esplora-stripprefix.stripprefix.prefixes=/esplora,/esplora/
        # - traefik.http.middlewares.esplora-stripprefix.stripprefix.forceSlash=true
        - traefik.http.middlewares.esplora-auth.basicauth.users=<username:bcrypt>
      replicas: 1
      placement:
        constraints:
          - node.labels.io.cyphernode == true
      restart_policy:
        delay: 1s
      update_config:
        parallelism: 1
networks:
  cyphernodeappsnet:
    external: true
